[package]
name = "conductor-nodes"
version = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[dependencies]
conductor-core = { workspace = true }
conductor-macros = { workspace = true }
