[package]
name = "conductor-sim"
version = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[dependencies]
clap = { workspace = true }
csv = "1.3.0"
serde = { version = "1.0.205", features = ["derive"] }
