[package]
name = "conductor-macros"
version = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[dependencies]
syn = "2.0.75"
quote = "1.0.37"

[lib]
proc-macro = true
